CREATE DATABASE db_todo;
use db_todo;

DROP TABLE if exists 'tag';
CREATE TABLE `tag` (
  `TAGID` int NOT NULL AUTO_INCREMENT,
  `TNAME` varchar(50) DEFAULT NULL,
  `TEXTCOLOR` varchar(6) DEFAULT NULL,
  `BACKCOLOR` varchar(6) DEFAULT NULL,
  `TDATE` date DEFAULT NULL,
  PRIMARY KEY (`TAGID`),
  UNIQUE KEY `nameindex` (`TNAME`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

DROP TABLE if exists 'todoList';
CREATE TABLE `todoList` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `TITLE` varchar(200) DEFAULT NULL,
  `CONTENT` varchar(1000) DEFAULT NULL,
  `TAG` varchar(50) DEFAULT NULL,
  `WDATE` date DEFAULT NULL,
  `UDATE` date DEFAULT NULL,
  `TARGETDATE` date DEFAULT NULL,
  `FDATE` date DEFAULT NULL,
  `FINISHCHECK` tinyint(1) DEFAULT NULL,
  `TAGID` int DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
